### PR TITLE
Fix wrong types for nested record fields

### PR DESCRIPTION
**Pull request by amiralies**
This is a temporarily fix for https://github.com/rescript-lang/rescript-vscode/issues/52

### CODE REVIEW

**Comment by amiralies** [comment]
Before:
image

After:
image

**Comment by cristianoc** [comment]
Thanks a lot for this.
About expanding type `group` with its definition, I'm not sure. As another example is e.g. `memberOf: (group, group)` where one would definitely not expand `group`.

**Comment by amiralies** [comment]
Yeah I think the same in fact typescript language server and merlin/ocamllsp have similar behaviour.

**Comment by cristianoc** [comment]
Continued this in a more extensive PR: https://github.com/rescript-lang/rescript-editor-support/pull/48.

**Pull request closed without merging**
